### ISSUE TITLE
AutoReconnectLib missing.

### ISSUE THREAD

**Issue by mibby** [AoElite/AutoReconnect#1]
@AoElite Trying to compile the latest source for the bug-fix, I noticed the dependency AutoReconnectLib cannot be found.

https://github.com/AoElite/AutoReconnect/blob/master/pom.xml#L82

Do you perhaps have a repo where it is hosted / can be compiled? I'm unable to compile the source without it.

**Comment by PseudoResonance** [comment]
I realize this is pretty late, but for anyone checking, AutoReconnectLib isn't an actual dependency. I'm not sure why it's in there, but it's not in use anywhere, and as you found, it's not something available online. It can be safely removed and the plugin will compile.
