### ISSUE TITLE
1.16.1 Plugin Not Enabling

### ISSUE THREAD

**Issue by BluLightShow** [AoElite/AutoReconnect#11]
![AjlNH](https://user-images.githubusercontent.com/20815595/86304091-5eba9080-bbd3-11ea-9542-ea69f27c861c.png)
Error is attached, plugin is not loading or enabling on latest Waterfall 1.16.1. No config file is generated.

**Comment by BluLightShow** [comment]
(Server version is latest PaperSpigot if applicable)

**Comment by PseudoResonance** [comment]
Sorry, I made a mistake when making Protocolize optional. I've fixed it in the new update I am pushing.
[AutoReconnect-1.5.jar.zip](https://github.com/AoElite/AutoReconnect/files/4874008/AutoReconnect-1.5.jar.zip)
Here's a download of the new jar file if you would like it before it is uploaded to Spigot.

**Comment by BluLightShow** [comment]
No need to apologize, glad it’s fixed up, amazing work with this plugin! I’ll be sure to install it soon!
