### ISSUE TITLE
Logic error in 1.16+

### ISSUE THREAD

**Issue by Xernium** [AoElite/AutoReconnect#13]
The code found under:     
https://github.com/AoElite/AutoReconnect/blob/master/src/main/java/me/aoelite/bungee/autoreconnect/AutoReconnect.java#L207   
Is flawed for use in 1.16 and newer.     
I need to point out that in 1.16 and newer, the registry that is sent on initial join will determine the valid values here. 
You either have to track all of these values correctly and make sure that the origin and target registries match; or resend a join game packet for 1.16 clients.     
That said- fake switching is dead for that very reason.      
Also do take note that the dimension identifier is an NBT tag and not a string nor an integer in 1.16.2 and newer     

Please refer to https://github.com/SpigotMC/BungeeCord/pull/2861 for further explanation. If you want need further information please feel free to ask. I warmly recommend you read this entire PR and watch the attached videos, as well as have a look at the proposed additional PR closer to the end of the discussion.

**Comment by PseudoResonance** [comment]
Thank you for pointing this out, I didn't think to check if the protocol had changed between 1.16.1 and 1.16.2.
Do you think that just sending a custom login packet to move them to a new world would be the ideal solution in this case?
