### ISSUE TITLE
Does not work on one server.

### ISSUE THREAD

**Issue by DrWackyBob** [AoElite/AutoReconnect#27]
It works and reconnects users on all other servers apart from the smp where it just goes straight to the server closed message. 
This is the bungee console log - https://pastebin.com/upcmzTS7
Any help will be appreciated

**Comment by DrWackyBob** [comment]
Hi just read through the config again and i think i may have found the issue. Its to do with the regex as the server closed message is different.

**Comment by PseudoResonance** [comment]
Have you solved the issue?

**Comment by PseudoResonance** [comment]
Closing the issue as I'm assuming it has been resolved.
