### ISSUE TITLE
Plugin version 1.6.5 (MC 1.17 support) is not compatible with older Java version

### ISSUE THREAD

**Issue by imparium-de** [AoElite/AutoReconnect#28]
Heya!
Not sure if that's intentional or not, but your newest update isn't compatible with older Java versions. We know that Java 16 will soon be mandatory because Paper and big plugins will update, but there are still a lot of plugins that haven't updated to MC 1.17 or Java 16 respectively. We for example are still on 1.16.5 with Java 11 because of this. Is there a way to make this plugin downward compatible?

Best regards,
Imparium.de <3 

Error: https://paste.gg/p/anonymous/d6ba7163b0a6456baa126f38afc07d53

**Comment by PseudoResonance** [comment]
It's a BungeeCord plugin though, and you should always be running the latest BungeeCord version, which I am pretty sure is moving towards Java 16. I guess I could move it back to Java 11, as it doesn't utilize anything from Java 16.

Although before anyone else asks, Java 8 is far too old and shouldn't be in use anymore for without good reason.

**Comment by PseudoResonance** [comment]
Fixed in 618d40e
