### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by MAXOUXAX** [AoElite/AutoReconnect#30]
The plugin works very well with BungeeCord and I think its features are essential when it comes to running a Minecraft network.
While BungeeCord is probably still the most widely used proxy for Minecraft, Velocity is slowly but surely attracting more and more users every day thanks to its better performance and almost identical if not better features.

It would be great if this plugin worked with Velocity (while maintaining BungeeCord support of course) 👍

**Comment by PseudoResonance** [comment]
Hopefully version 2.0.0 and above will support Velocity as well. I believe it is most likely possible, although it may come in a slightly later update instead.

**Comment by OverBrave** [comment]
I hope this update comes as soon as possible, I need it very much. I switched to Velocity because the BungeeCord problems were overwhelming me and I'm more happy now, but such plugins need immediate support.

**Comment by democracycraft** [comment]
Yes please!!

**Comment by ruby-lys** [comment]
Yeah same here!!

**Comment by WayPlay** [comment]
up =)
