### ISSUE TITLE
InaccessibleObjectException

### ISSUE THREAD

**Issue by WongIong** [AoElite/AutoReconnect#35]
i get this warning when i join the server

Could not save LimboPlayer for 'WongIong' [InaccessibleObjectException]: Unable to make private java.util.Collections$EmptyList() accessible: module java.base does not "opens java.util" to unnamed module @2cbb3d47

**Comment by PseudoResonance** [comment]
Is there any more information in the error? Can you enable debug logging in the plugin config and show the log output?

**Comment by WongIong** [comment]
It just happens on 1.17 server. nothing shows on bungeecord

**Comment by PseudoResonance** [comment]
I still have no idea what this was, but you can try the newest version, [1.6.7](https://github.com/AoElite/AutoReconnect/files/7867267/AutoReconnect-1.6.7.jar.zip), I have tested it and it works on 1.18.1.

**Comment by WongIong** [comment]
Oh i forgot about this,
seems this issue is related to windows or paper either one
And paper said they have already fixed it
Thank you!
