### ISSUE TITLE
1.18 doesnt reconnect

### ISSUE THREAD

**Issue by BG-D7** [AoElite/AutoReconnect#39]
I use 1.18 bungee and flamecord
When i restart backend 1.18 server proxy kick my players
With 1.12 server all works good

**Comment by PseudoResonance** [comment]
Sorry about the confusion, I didn't realize until today what was wrong, because in 1.18.2, Mojang added 1 character to a tag value and I just never noticed it was different... I've updated the plugin for 1.18.2 and 1.19 though today and have tested every version from 1.15 to 1.19.
