### ISSUE TITLE
Waterfall Version 327, 344 and BungeeCord version 1499 (Latest)

### ISSUE THREAD

**Issue by PrinceBunBun981** [AoElite/AutoReconnect#4]
When on this version it will just kick the person with the "Server Closed" message when the server shuts down. There's no errors in the console about it either. And this only happens when I edit anything in the confix, messages, settings, etc.

**Comment by PseudoResonance** [comment]
Is the plugin loaded at startup? It should say something like `Enabled plugin AutoReconnect version 1.3 by null`.

**Comment by PrinceBunBun981** [comment]
Yes it loads.

**Comment by PseudoResonance** [comment]
Sorry, I have no idea what it could be cause there's no errors, but I guess you could try my build of the plugin. It's in a pull request right now, but I modernized some of the code to use BungeeCord's new methods and added a little check to try and fix running it on older versions of BungeeCord. Not sure if it will fix it, but it should be able to run on a wider range of versions.

https://github.com/AoElite/AutoReconnect/files/4708730/AutoReconnect-1.3.jar.zip

**Comment by PseudoResonance** [comment]
No reply, so assuming issue is resolved.
