### ISSUE TITLE
breaks bungeecord locations

### ISSUE THREAD

**Issue by Ceddix** [AoElite/AutoReconnect#41]
Hey, since 1.19 this plugin seems to break the bungee functionality, that if you join the network you join at the server where you log out _(saved in locations.yml)_.

**Comment by PseudoResonance** [comment]
I'll try to take a look soon, but I am currently recovering from surgery, so I'm sorry if it takes a while. I'm guessing [this part](https://github.com/AoElite/AutoReconnect/blob/master/src/main/java/me/aoelite/bungee/autoreconnect/net/ReconnectBridge.java#L82=) just needs to be updated.

**Comment by Ceddix** [comment]
Thank you!

No stress - I hope you get well soon :)

**Comment by Ceddix** [comment]
Hey, I hope you're feeling better! 😄 
Is there any news about this bug or have you not had the chance yet?

**Comment by PseudoResonance** [comment]
Sorry! I've been working on updating to 1.19.1, but it's a lot harder because the Minecraft protocol wiki isn't being updated. Also I actually had to get a 2nd corrective surgery done hours ago, which hasn't been fun either haha. Hopefully soon. I've got it mostly figured out.

**Comment by Ceddix** [comment]
So I've updated the plugin and `/glist` seems to be working properly again.

However, as you said, the locations still don't work. It seems to be somehow due to AutoReconnect, because as soon as I remove the plugin, it saves the location again.
I think it still has to do something with the disconnect event 🤔 

Get well soon because of your operation! And thanks for your help!

**Comment by PseudoResonance** [comment]
Thank you! Are you running Waterfall or another fork of BungeeCord, or just BungeeCord?

**Comment by Ceddix** [comment]
I'm running Waterfall

**Comment by PseudoResonance** [comment]
Oh I finally realized what was wrong. The new 1.6.11 update should resolve it.

**Comment by Ceddix** [comment]
Yes, now it works again. Thanks a lot for your help!
