### ISSUE TITLE
Limbo

### ISSUE THREAD

**Issue by minster586** [AoElite/AutoReconnect#42]
so i was wondering as i want to use Link below as limbo can I have it push them there and do the same thing once the server comes back up online just wondering

https://www.spigotmc.org/resources/limbo-standalone-server-lightweight-solution-for-afk-or-waiting-rooms-in-your-server-network.82468/

**Comment by PseudoResonance** [comment]
I've been planning to add support for this, but it is not currently available. I'm still waiting for the 1.19.1 protocol documentation to update to that.

**Comment by minster586** [comment]
ok thanks
