### ISSUE TITLE
(feature request) move song track from "music" to "master"

### ISSUE THREAD

**Issue by DarkKingKaan** [AoElite/AutoReconnect#43]
Most people have their music set to 0%, making it impossible to hear the reconnecting music I set in the config.

I feel like the music should be moved from the "music" track to "master", or at least make it configurable, so that no matter the player's settings, they will hear the music unless their whole game is muted.

Thanks for considering! :)

**Comment by PseudoResonance** [comment]
The music is handled by the client. The plugin simply tells it what ambient music should be played, just like any other biome in the game. Either way, is the point of the music slider not to disable music?...

**Comment by DarkKingKaan** [comment]
I'd like everyone to hear the custom track I imported no matter their client-side settings, therefore playing the music on master track is the only workaround I can think of.

Is there a way for me to do it myself? For example, when using the `/playsound` command (built-in) I can specify the track (music, ambient, master etc.). So if the player has music turned off (which is the case most of the time), they'll still be able to hear it, since it's playing on the master track, unless their whole game is muted.

**Comment by PseudoResonance** [comment]
You could get some kind of plugin for the proxy that sends a sound packet when they join the server.
