### ISSUE TITLE
[Bug?] Max-Reconnect-Tries is bad

### ISSUE THREAD

**Issue by Texbio** [AoElite/AutoReconnect#45]
The issue with it though is that the autoreconnect tries (max-reconnect-tries) is very useless cause the plugin still tries to connect to the main server when the main server is loading plugins which leads the player to be stuck in the limbo world.

To get around this I need to set my delay to 3 minutes (server takes 2m 30s to load) so no issues occur with the player not connecting and disabling max-reconnect-tries completely. If there is another fix please tell me since I got no idea what I could have missed.

There should be a way to detect if the main server has completely loaded or not either through a plugin on the main server or some other way of pinging the main server.

**Comment by Texbio** [comment]
It also has the issue where if the reconnect failed due to a minecraft error like connection time out, it does not try reconnecting again, it just keeps the player stuck in limbo. Would be great if these 2 issues were fixed

**Comment by Texbio** [comment]
accidently closed

**Comment by PseudoResonance** [comment]
Duplicates #24. I was working on this, but there's actually no good way to tell when a server is ready, even from the plugin side for some reason. I've been pretty busy with school, so my plan was to finish it over the summer of 2022, but sadly I had to get surgery, so I wasn't able to. Sorry for the delay.
