### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by ProSharkyt** [AoElite/AutoReconnect#6]
the plugin isn't being detected by bungee cord. 1.15.2

**Comment by PseudoResonance** [comment]
Are you using the latest version of the plugin, 1.2? It fixes support with 1.15.2.

**Comment by PseudoResonance** [comment]
For 1.16, here is an updated build that supports it.
[AutoReconnect-1.4.jar.zip](https://github.com/AoElite/AutoReconnect/files/4827956/AutoReconnect-1.4.jar.zip)

**Comment by PseudoResonance** [comment]
No reply, so assuming issue is resolved.
